#RequireAdmin
;~ ControlSetText('Auto Update','','[Class:TAdvEdit; Instance:1]','AAABAOBNBCODEUNB0XPAEOK8JSQF6WZY')

While 1
$txt=FileReadLine('E:\Minh\Documents\nqbcode1.txt',1)
Sleep(100)
$hwd=FileOpen('E:\Minh\Documents\nqbcode1.txt',2)
$txt2=InputBox('','',$txt)
FileWrite($hwd,$txt2)
FileClose($hwd)
ControlFocus('Fiddler Web Debugger','','[Class:WindowsForms10.SysListView32.app.0.33c0d9d]')
Sleep(100)
ControlSend('Fiddler Web Debugger','','','^{x}')
Sleep(100)
ControlClick('Auto Update','','[Class:TAdvGlowButton; Instance:2]')
Sleep(100)
MouseClick('left',82, 110,1,0)
Sleep(100)
ControlSetText('Fiddler Web Debugger','','[Class:WindowsForms10.RICHEDIT50W.app.0.33c0d9d; Instance:1]',$txt2)
Sleep(100)
;~ ControlFocus('Fiddler Web Debugger','Run to &Completion','[Class:WindowsForms10.BUTTON.app.0.33c0d9d; Instance:4]')
;~ ControlClick('Fiddler Web Debugger','Run to &Completion','[Class:WindowsForms10.BUTTON.app.0.33c0d9d; Instance:4]')
MouseClick('left',623, 382,1,0)
Sleep(100)
WinWait('Error')
Sleep(100)
WinClose('Error')
Sleep(100)
WEnd