#include <IE.au3>
#include <String.au3>
;~ #include <Array.au3>
;~ #RequireAdmin
Global $final=''
;~ ControlSetText('Choose File to Upload','','[Class: Edit ;Instance: 1]','captcha.jpg')
;~ ControlClick('Choose File to Upload','','[Class: Button ;Instance: 1]')
;~ WinClose('Message from webpage')
;~ $i=FileRead(@DesktopDir&'\Yes24.txt')
;~ $name='hthm'&$i

;~ $ie4=_IECreate('http://www.yes24.vn/Member/LoginPop.aspx')
;~ 	$form1=_IEFormGetObjByName($ie4,'form1')
;~ 	$user=_IEFormElementGetObjByName($form1,'txtUserId')
;~ 	_IEFormElementSetValue($user,$name)
;~ 	$passhover=_IETagNameGetCollection($ie4,'span',1)
;~ 	_IEAction($passhover,'click')
;~ 	$pass=_IEFormElementGetObjByName($form1,'txtPassword')
;~ 	_IEAction($pass,'click')
;~ 	_IEFormElementSetValue($pass,'minh188')
;~ 	$sub=_IEGetObjById($ie4,'btnLogin')
;~ 	_IEAction($sub,'click')
;~ 	Sleep(2000)

;~ 	$ie5=_IECreate('http://www.yes24.vn/event-2016/vong-xoay-may-man?scr=home_hotb')
;~ 	_IELoadWait($ie5)
;~ 	WinSetState('Vòng quay may mắn - Yes24 Việt Nam - Internet Explorer','',@SW_MAXIMIZE)
;~ 	Sleep(1000)
;~ 	ControlSend('Vòng quay may mắn - Yes24 Việt Nam - Internet Explorer','','','{space}')
;~ 	Sleep(1000)
;~ 	MouseClick('left',491, 279,1,0)
;~ 	Sleep(3000)
;~ 	$quay=_IEGetObjById($ie5,'btnQuay')
;~ 	$quay=_IETagNameGetCollection($ie5,'div',58)
;~ 	_IEAction($quay,'click')
;~ 	_IEQuit($ie4)
;~ Exit

HotKeySet('{f4}','_exit')

$i=FileRead(@DesktopDir&'\Yes24.txt')
$name='hthm'&$i
$ie=_IECreate('http://www.yes24.vn/Member/MemberJoinPop.aspx')
$form1=_IEFormGetObjByName($ie,'form1')
$user=_IEFormElementGetObjByName($form1,'txtUserId')
_IEFormElementSetValue($user,$name)

$txt=_IEBodyReadHTML($ie)
;~ ClipPut(_IEBodyReadHTML($ie))
$file=_StringBetween($txt,'width: 162px; height: 40px;" src="','"></li>')
$file1=StringReplace($file[0],'amp;','')
InetGet('http://www.yes24.vn/'&$file1,@DesktopDir&'\captcha.jpg')
$link='http://www.yes24.vn/'&$file1
ClipPut($link)

;~ $ie2=_IECreate('https://www.newocr.com/',0,0)
;~ $form=_IEFormGetObjByName($ie2,'form')
;~ $hinh=_IEFormElementGetObjByName($form,'userfile')
;~ _IEAction($hinh,'click')
;~ $preview=_IEGetObjById($ie2,'preview')
;~ _IEAction($preview,'click')
;~ _IELoadWait($ie2)
;~ $ocr=_IEGetObjById($ie2,'ocr')
;~ _IEAction($ocr,'click')
;~ _IELoadWait($ie2)
;~ $captxt=_IEBodyReadText($ie2)
;~ $remove=StringReplace($captxt,'(adsbygoogle = window.adsbygoogle || []).push({});','')
;~ $code=_StringBetween($remove,'Edit Online','© NewOCR.com 2009 - 2016')
;~ If Not @error Then
;~ 	$final=StringReplace($code[0],' ','')
;~ 	_IEQuit($ie2)
	Sleep(1000)
	WinSetState('http://www.yes24.vn/Member/MemberJoinPop.aspx - Internet Explorer','',@SW_MAXIMIZE)
	Sleep(1000)
	MouseClick('left',259, 138,1,0)
	Sleep(1000)
	MouseClick('left',234, 145,1,0)
	$passhover=_IETagNameGetCollection($ie,'span',1)
	_IEAction($passhover,'click')
	$pass=_IEFormElementGetObjByName($form1,'txtPassword')
	_IEAction($pass,'click')
	_IEFormElementSetValue($pass,'minh188')
	Sleep(500)
	$passhover2=_IETagNameGetCollection($ie,'span',2)
	_IEAction($passhover2,'click')
	$pass2=_IEFormElementGetObjByName($form1,'txtPassword2')
	_IEAction($pass2,'click')
	_IEFormElementSetValue($pass2,'minh188')
	$email=_IEFormElementGetObjByName($form1,'txtEmail')
	_IEFormElementSetValue($email,$name&'@get.pp.ua')
	;~ $gender=_IEFormElementGetObjByName($form1,'rbGenderList')
	;~ _IEFormElementRadioSelect($gender,'Nam','rbGenderList')
	$gender=_IEGetObjById($ie,'rbGenderList_0')
	_IEAction($gender,'click')
	$ma=_IEFormElementGetObjByName($form1,'txtCaptcha')
	$final2=InputBox('Mã là','',$final)
	$captcha=$final2
	_IEFormElementSetValue($ma,$captcha)
	$sub=_IEGetObjById($ie,'btnRegistMember')
	_IEAction($sub,'click')
	;~ _IEFormSubmit($form1)
	Do
		Sleep(500)
		ToolTip('Waiting',10,10)
	Until WinExists('Message from webpage')
;~ 	MsgBox(0,'','')
	If WinExists('Message from webpage') Then
;~ 		MsgBox(0,'','1')
		If ControlGetText('Message from webpage','','[Class:Static; Instance:2]')='Đăng ký tài khoản thành công. Vui lòng kiểm tra Email để kích hoạt tài khoản.' Then
			WinClose('Message from webpage')
			ToolTip('OK',10,10)
			_IEQuit($ie)
			Sleep(10000)
			xacnhan()
			ff()
			$i=FileRead(@DesktopDir&'\Yes24.txt')
			$yes24=FileOpen(@DesktopDir&'\Yes24.txt',2)
			FileWrite($yes24,$i+1)
			FileClose($yes24)
;~ 			MsgBox(0,'','OK')
		ElseIf ControlGetText('Message from webpage','','[Class:Static; Instance:2]')='Địa chỉ email đã được đăng nhập.' Then
			ToolTip('Đã đăng ký',10,10);http://www.yes24.vn/image/SMTP/EmailRegMember_11.gif
;~ 			MsgBox(0,'','');Xác nhận tài khoản thành công. Mời quý khách đăng nhập
			WinClose('Message from webpage')
			_IEQuit($ie)
			xacnhan()
			ff()
			$i=FileRead(@DesktopDir&'\Yes24.txt')
			$yes24=FileOpen(@DesktopDir&'\Yes24.txt',2)
			FileWrite($yes24,$i+1)
			FileClose($yes24)
		Else
;~ 			MsgBox(0,'','Failed')
			WinClose('Message from webpage')
			$i=FileRead(@DesktopDir&'\Yes24.txt')
			$yes24=FileOpen(@DesktopDir&'\Yes24.txt',2)
			FileWrite($yes24,$i-1)
			FileClose($yes24)
			_IEQuit($ie)
		EndIf
	EndIf
;~ Else
;~ 	_IEQuit($ie)
;~ 	_IEQuit($ie2)
;~ 	$i=FileRead(@DesktopDir&'\Yes24.txt')
;~ 	$yes24=FileOpen(@DesktopDir&'\Yes24.txt',2)
;~ 	FileWrite($yes24,$i-1)
;~ 	FileClose($yes24)
;~ EndIf
;~ _IEQuit($ie)
Run('E:\Minh\AutoIT\Autoyes24-bonus.exe')

Func xacnhan()
	$ie3=_IECreate('http://email-fake.com/get.pp.ua/'&$name)
	$table=_IEGetObjById($ie3,'email-table')
	$mail=_IETagNameGetCollection($table,'a',0)
	_IEAction($mail,'click')
	_IEImgClick($ie3,'http://www.yes24.vn/image/SMTP/EmailRegMember_11.gif')
	Do
		Sleep(500)
		ToolTip('Waiting',10,10)
	Until WinExists('Message from webpage')
	WinClose('Message from webpage')
	_IEQuit($ie3)
	ProcessClose('iexplore.exe')
;~ 	$ie4=_IECreate('http://www.yes24.vn/Member/LoginPop.aspx')
;~ 	$form1=_IEFormGetObjByName($ie4,'form1')
;~ 	$user=_IEFormElementGetObjByName($form1,'txtUserId')
;~ 	_IEFormElementSetValue($user,$name)
;~ 	$passhover=_IETagNameGetCollection($ie4,'span',1)
;~ 	_IEAction($passhover,'click')
;~ 	$pass=_IEFormElementGetObjByName($form1,'txtPassword')
;~ 	_IEAction($pass,'click')
;~ 	_IEFormElementSetValue($pass,'minh188')
;~ 	$sub=_IEGetObjById($ie4,'btnLogin')
;~ 	_IEAction($sub,'click')
EndFunc
Func ff()
	WinActivate('Vòng quay may mắn - Yes24 Việt Nam - Mozilla Firefox (Private Browsing)')
	Sleep(500)
	MouseClick('left',330, 17,1,0)
	Sleep(500)
;~ 	MouseClick('left',275, 53,1,0)
;~ 	Sleep(500)
;~ 	Send('^{a}')
;~ 	Sleep(500)
;~ 	Send('http://www.yes24.vn/Member/LoginPop.aspx')
;~ 	Send('{enter}')
;~ 	Sleep(2000)
	MouseClick('left',85, 141,1,0)
	Sleep(500)
	Send($name)
	Sleep(500)
	MouseClick('left',77, 193,1,0)
	Sleep(500)
	MouseClick('left',77, 193,1,0)
	Sleep(500)
	Send('minh188')
	Sleep(500)
	MouseClick('left',187, 290,1,0)
	Sleep(2000)
	MouseClick('left',117, 18,1,0)
	Sleep(500)
	Send('{F5}')
;~ 	Sleep(5000)
;~ 	Send('{space}')
	Sleep(5000)
	MouseClick('left',490, 455,1,0)
	Sleep(1000)
	Send('{enter}')
	MouseClick('left',490, 455,1,0)
	Sleep(1000)
	Send('{enter}')
	MouseClick('left',490, 455,1,0)
	Send('{enter}')
	Sleep(500)
	Send('{enter}')
	Sleep(500)
	Send('{enter}')
	Sleep(500)
	Send('{enter}')
	Sleep(500)
	Send('{enter}')
	Sleep(500)
EndFunc

Func _exit()
Exit
EndFunc